# Generated by Django 3.2.4 on 2023-12-08 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import utilities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=utilities.models.get_image_path, verbose_name='Image')),
                ('image_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='caption')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=utilities.models.get_video_file_path)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(blank=True, related_name='interest_blogs', to='user_profile.Interest')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('tags', models.ManyToManyField(blank=True, related_name='tag_blogs', to='user_profile.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
